os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

cache: yarn

env:
  jobs:
    - TARGET=packages/web
    - TARGET=packages/api

before_install:
  - cd $TARGET
install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn build
