version: "3.8"

services:
  redis:
    image: redis:6.2.3
  s3:
    image: minio/minio:RELEASE.2021-05-20T22-31-44Z
    entrypoint: sh
    command: -c "mkdir -p /data/tarnhelm-storage && /usr/bin/minio server /data"
  api:
    build:
      context: .
    depends_on:
      - redis
      - s3
    init: true
    environment:
      LND_SOCKET: socket
      LND_MACAROON: macaroon
      REDIS_URL: redis://redis:6379
      S3_ACCESS_KEY_ID: minioadmin
      S3_ACCESS_KEY_SECRET: minioadmin
      S3_ENDPOINT: http://s3:9000
      S3_BUCKET: tarnhelm-storage
    # command: ["./wait-for-it.sh", "redis:6379", "--strict", "&&", "./wait-for-it.sh", "s3:9000", "--strict", "--", "yarn", "start"]
    command: ["yarn", "start"]
    # restart: unless-stopped
    ports:
      - "7089:7089"
    # healthcheck:
    #   test:
    #     ["CMD", "curl", "-f", "http://localhost:7089", "||", "exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
