version: "3.8"

services:
  redis:
    image: redis:6.2.3
    ports:
      - "6379:6379"
  s3:
    image: minio/minio:RELEASE.2021-05-20T22-31-44Z
    entrypoint: sh
    command: -c "mkdir -p /data/tarnhelm-storage && /usr/bin/minio server /data"
    ports:
      - "9000:9000"
