version: "3.8"

services:
  redis:
    image: redis:6.2.3
    ports:
      - "6379:6379"
  s3:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    entrypoint: sh
    command: -c "mkdir -p /data/tarnhelm-storage && /usr/bin/minio server /data" # Creates default `tarnhelm-storage` bucket and starts the server
    ports:
      - "9000:9000"
